### ISSUE TITLE
Increase test coverage to 100%

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/fastify-jwt-authz#2]
Using `node-tap` increase the code coverage to 100% across all branches. Add the travis markdown widget to the README. This module will support Node.JS 4+.

**Comment by Ethan-Arrowood** [comment]
[Travis-CI](https://travis-ci.org/Ethan-Arrowood/fastify-jwt-authz)

**Comment by benceHornyak** [comment]
Hi
Can you give me some lead to get started?

**Comment by benceHornyak** [comment]
Hi
Can you give me some lead to get started?

**Comment by Ethan-Arrowood** [comment]
Hi @benceHornyak! 

I'll try to keep this as simple as possible, but let me know if you want me to expand on anything.
1. Fork this repository and clone it locally to your computer.
2. Create a new branch and set up the project (`npm install`)
3. Locate `test.js` and read the documentation for [`node-tap`](http://www.node-tap.org/)
4. Write unit tests and try to get the code coverage up to 100% (you can get coverage reporting by running `npm run test -- --coverage`. 
5. Commit and push to your branch frequently. 
6. When you think you have something ready for me to review create a pull request from your branch onto `fastify-jwt-authz/master`. 
7. I'll review your code and give you feedback
8. Fix anything I review, then commit and push again.
9. I'll continue to review until I believe it is ready to merged. And then that'll be it! 🎉

**Comment by benceHornyak** [comment]
@Ethan-Arrowood 
I've read the documentation for node-tap, but after that I am just stuck.. Tried to play around to call checkScopes() but I couldn't get it.. can you help me a little? 
Tried to copy the existing test and modify it but didn't work

**Comment by Ethan-Arrowood** [comment]
You won't be calling `checkScopes()` directly. The module is registered on the `request` instance of fastify. See on line 14 https://github.com/Ethan-Arrowood/fastify-jwt-authz/blob/56bff85a92e0b4d694aeae2c3ff5f3a01eec4a9b/test.js#L14 how the test file is verifying that `request.jwtAuthz` exists? This is how you call the method 😄

**Comment by benceHornyak** [comment]
This was the part that I was missing..
https://github.com/Ethan-Arrowood/fastify-jwt-authz/blob/56bff85a92e0b4d694aeae2c3ff5f3a01eec4a9b/fastify-jwt-authz.js#L7
Initially I was thinking the call would look like something like `request.jwtAuthz.checkScopes(foo, bar)`

**Comment by Ethan-Arrowood** [comment]
Closing with #5
